### PR TITLE
fix(widgets): fix centered block title truncation

### LINKED ISSUE #1936: Centered block titles truncate oddly
## Description
Truncation of Centered titles truncate the titles one by one rather than the whole list of titles.

## To Reproduce

```rust
    #[test]
    fn center_titles_truncated() {
        let mut buffer = Buffer::empty(Rect::new(0, 0, 10, 1));
        Block::new()
            .title(Line::from("C12345").centered())
            .title(Line::from("C67890").centered())
            .render(buffer.area, &mut buffer);
        assert_eq!(buffer, Buffer::with_lines(["C12345 678"])); // incorrect current behavior
    }
```

## Expected behavior

The expected result should be "12345 C678" or "2345 C6789".
I forget how we choose between centering odd character counts in even spaces, but this should be consistent with all other usages.

### PR DESCRIPTION
**Pull request by ognis1205**
## Description

- Expose `ratatui_core::text::Line::spans_after_width` using `#[doc(hidden)]` to support the expected behavior in `ratatui_widgets::Block::render_center_title`.
- Considered refactoring `spans_after_width` into a proper method on the `Line` struct, but opted against it to avoid introducing new public APIs in a bugfix-oriented PR.
- Also considered adding a `skip_width: Option<usize>` field to `Line`, but decided against it for the same reason.

## Related Issue

Closes #1936

## Checklist

- [x] All unit tests pass
- [x] Added regression test for multi-title center truncation
- [x] Documentation updated if necessary

### CODE REVIEW

**Comment by ognis1205** [comment]
cc: @joshka 

This PR is ready for your review when convenient. Let me know if anything needs clarification!

File: ratatui-widgets/src/block.rs [hunk 1]
```diff
@@ -933,41 +933,80 @@ impl Block<'_> {
     }
 
     /// Render titles in the center of the block
-    ///
-    /// Currently this method aligns the titles to the left inside a centered area. This is not
-    /// ideal and should be fixed in the future to align the titles to the center of the block and
-    /// truncate both sides of the titles if the block is too small to fit all titles.
     #[expect(clippy::similar_names)]
     fn render_center_titles(&self, position: TitlePosition, area: Rect, buf: &mut Buffer) {
```
Comment (joshka) [inline ratatui-widgets/src/block.rs:936]: This method is now a bit longer than I'd ideally like to see (~75 Loc). I started looking at how this might be broken up a bit and ended up with something that's a bit smaller.

File: ratatui-widgets/src/block.rs [hunk 2]
```diff
@@ -933,41 +933,80 @@ impl Block<'_> {
...
             .collect_vec();
         let total_width = titles
             .iter()
-            .map(|title| title.width() as u16 + 1) // space between titles
+            // Add space width between titles.
+            .map(|title| title.width() as u16 + 1)
             .sum::<u16>()
-            .saturating_sub(1); // no space for the last title
+            // Remove redundant space width, i.e., the trailing one.
+            .saturating_sub(1);
```
Comment (joshka) [inline ratatui-widgets/src/block.rs]: I changed the comments a bunch to be more succinct

File: ratatui-widgets/src/block.rs [hunk 3]
```diff
@@ -933,41 +933,80 @@ impl Block<'_> {
...
-                break;
-            }
-            let title_width = title.width() as u16;
-            let title_area = Rect {
-                width: title_width.min(titles_area.width),
+        // If the total title width fits within the available area, center the titles.
+        if total_width <= titles_area.width {
+            // Adjust the rendering area to center the titles horizontally.
+            titles_area = Rect {
+                x: titles_area.left() + (titles_area.width.saturating_sub(total_width) / 2),
```
Comment (joshka) [inline ratatui-widgets/src/block.rs]: Added more temp vars to help make the line density a bit lower

File: ratatui-widgets/src/block.rs [hunk 4]
```diff
@@ -933,41 +933,80 @@ impl Block<'_> {
...
             };
-            buf.set_style(title_area, self.titles_style);
-            title.render(title_area, buf);
-
-            // bump the titles area to the right and reduce its width
-            titles_area.x = titles_area.x.saturating_add(title_width + 1);
-            titles_area.width = titles_area.width.saturating_sub(title_width + 1);
+            for title in titles {
+                if titles_area.is_empty() {
+                    break;
```
Comment (joshka) [inline ratatui-widgets/src/block.rs]: This check is not necessary for area > width - it will never be triggered (codecov agrees)

File: ratatui-widgets/src/block.rs [hunk 5]
```diff
@@ -933,41 +933,80 @@ impl Block<'_> {
...
+                        width: span_width.min(title_area.width),
+                        ..title_area
+                    };
+                    span.render(span_area, buf);
+                    // Move the rendering cursor to the right.
+                    titles_area.x = titles_area.x.saturating_add(span_width);
+                    titles_area.width = titles_area.width.saturating_sub(span_width);
+                });
+                // Advance skip_width by the full title width.
+                skip_width = skip_width.saturating_sub(title_width);
```
Comment (joshka) [inline ratatui-widgets/src/block.rs]: I replaced this with `title.clone().right_aligned().render(...)`, while it does do a clone of the line, the number of titles on screen and their length is likely not enough to worry about in any reasonable program, so I'm unconcerned about any performance hit on this.

File: ratatui-widgets/src/block.rs (hunk 1 above)
Comment (joshka) [reply ratatui-widgets/src/block.rs:936]: With my changes it's down to 50, which is still a bit high. Suggestions below to address that.

File: ratatui-widgets/src/block.rs [hunk 6]
```diff
@@ -933,41 +933,56 @@ impl Block<'_> {
...
-        let mut titles_area = Rect {
-            x: titles_area.left() + (titles_area.width.saturating_sub(total_width) / 2),
-            ..titles_area
-        };
-        for title in titles {
-            if titles_area.is_empty() {
-                break;
+            .saturating_sub(1);
+
+        if total_width <= area.width {
```
Comment (joshka) [inline ratatui-widgets/src/block.rs:948]: For reducing the size of this method, either:
- chop the inner part of the if blocks (e.g. render_center_titles_fitting, render_center_titles_exceeds); or
- see if the for loop can be factored so that the fitting and exceeds parts have a common implementation - these are fairly close with this new approach. I think probably extracting the methods is probably better as it makes it clear that the truncation code isn't necessary unless the titles are chopped.

File: ratatui-widgets/src/block.rs [hunk 7]
```diff
@@ -933,41 +933,56 @@ impl Block<'_> {
...
+            // is truncated by the area width.
+            let mut offset = total_width.saturating_sub(area.width) / 2;
+            for title in titles {
+                if area.is_empty() {
+                    break;
+                }
+                let width = area.width.min(title.width() as u16).saturating_sub(offset);
+                let title_area = Rect { width, ..area };
+                buf.set_style(title_area, self.titles_style);
+                buf.set_style(title_area, title.style);
```
Comment (joshka) [inline ratatui-widgets/src/block.rs]: not necessary as the title.render() call below sets this

File: ratatui-widgets/src/block.rs [hunk 8]
```diff
@@ -1946,6 +1971,16 @@ mod tests {
...
+        Block::new()
+            .title(Line::from("C12").centered())
+            .title(Line::from("C34").centered())
+            .render(buffer.area, &mut buffer);
+        assert_eq!(buffer, Buffer::with_lines([" C12 C34  "]));
+    }
+
     /// Note: this test is probably not what you'd expect, but it is how it works in the current
     /// implementation. Update this if the behavior changes.
     ///
```
Comment (joshka) [inline ratatui-widgets/src/block.rs]: Remove

**Review by joshka — COMMENTED** [review]
Self review of update

File: ratatui-widgets/src/block.rs (hunk 6 above)
Comment (j-g00da) [reply ratatui-widgets/src/block.rs:948]: First option sounds like the right way to go

**Review by j-g00da — CHANGES_REQUESTED** [review]
`render_center_titles` has to be split but other than that LGTM.

**Review by joshka — APPROVED** [review]

**Comment by joshka** [comment]
Thanks for the PR @ognis1205

**Comment by ognis1205** [comment]
@joshka @j-g00da 

Thanks for the merge and the refinements! Appreciate the cleanup — learned a lot from your refactor. Glad I could help!

In the original PR, I’ll start by outlining the intended behavior to clarify the spec. In addition to that, I’ll move forward with a PoC implementation. I might also start exploring another issue in parallel depending on bandwidth.
